spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

logging:
  level:
    root: INFO
    com.commercex: DEBUG
    org.hibernate.SQL: DEBUG
